[build-system]
requires = [
  "setuptools",
  "conan<2.0.0",
  "scikit-build>=0.11.0",
  "cmake!=3.17.1,!=3.17.0",
  "ninja",
  "pybind11>2.6",
  "oldest-supported-numpy; python_version>'3.7' or platform_machine=='aarch64' or platform_python_implementation=='PyPy'",
  "numpy==1.16.3; python_version<='3.7' and platform_machine!='aarch64' or platform_python_implementation=='PyPy'",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"
manylinux-s390x-image = "manylinux_2_28"
manylinux-ppc64le-image = "manylinux_2_28"
manylinux-i686-image = "manylinux2014"
skip = "pp* cp36* cp37* cp312* *musllinux*"
test-command = "python {project}/tools/verify_wheels.py"
environment = { AER_CMAKE_OPENMP_BUILD="1" }

[tool.cibuildwheel.linux]
before-all = "yum install -y openblas-devel"

[tool.cibuildwheel.windows]
environment = { CMAKE_GENERATOR = "Visual Studio 16 2019"}

[[tool.cibuildwheel.overrides]]
select = "*-manylinux_i686"
before-all = "yum install -y wget && bash {project}/tools/install_openblas_i686.sh && bash {project}/tools/install_rust.sh"

[[tool.cibuildwheel.overrides]]
select = "*-manylinux_{ppc64le,s390x}"
before-all = "yum install -y epel-release && yum install -y openblas-devel"

[[tool.cibuildwheel.overrides]]
select = "*-manylinux_aarch64"
before-all = "yum install -y https://dl.fedoraproject.org/pub/epel/7/aarch64/Packages/e/epel-release-7-12.noarch.rpm && yum install -y openblas-devel"

[tool.black]
line-length = 100
target-version = ['py38', 'py39', 'py310', 'py311']
